import { CropWorkflowConfig, WorkflowStageDefinition } from '../types/workflow';
import { CropType } from '../types';

export const STANDARD_STAGES: WorkflowStageDefinition[] = [
  {
    id: 'Crop Registered',
    label: 'Crop Registered',
    shortDescription: 'Farmer submitted crop details with geotagged photo proof',
    roleResponsible: 'farmer',
  },
  {
    id: 'Field Verified',
    label: 'Field Verified',
    shortDescription: 'Field Officer inspected geotagged field and approved legitimacy',
    roleResponsible: 'officer',
    requiredPreviousStage: 'Crop Registered',
  },
  {
    id: 'Procurement Pending',
    label: 'Procurement Pending',
    shortDescription: 'Verified crop queued for processing factory intake',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Field Verified',
  },
  {
    id: 'Procurement Scheduled',
    label: 'Procurement Scheduled',
    shortDescription: 'Factory assigned intake date, yard slot, and batch ID',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Procurement Pending',
  },
  {
    id: 'Harvest Scheduled',
    label: 'Harvest Scheduled',
    shortDescription: 'Coordinated harvest window confirmed with harvesting labor/machinery',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Procurement Scheduled',
  },
  {
    id: 'Transport Assigned',
    label: 'Transport Assigned',
    shortDescription: 'Factory or logistics partner vehicle and driver assigned for farm pickup',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Harvest Scheduled',
  },
  {
    id: 'In Transit',
    label: 'In Transit',
    shortDescription: 'Produce loaded and en route to the factory procurement center',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Transport Assigned',
  },
  {
    id: 'Arrived at Procurement Center',
    label: 'Arrived at Procurement Center',
    shortDescription: 'Vehicle checked in at mill weighbridge gate',
    roleResponsible: 'factory',
    requiredPreviousStage: 'In Transit',
  },
  {
    id: 'Quality Check',
    label: 'Quality Check',
    shortDescription: 'Laboratory quality parameters tested against fair-average-quality standards',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Arrived at Procurement Center',
  },
  {
    id: 'Weighment',
    label: 'Weighment',
    shortDescription: 'Gross and tare weights recorded on certified electronic weighbridge',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Quality Check',
  },
  {
    id: 'Accepted',
    label: 'Accepted',
    shortDescription: 'Produce accepted for industrial processing/crushing',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Weighment',
  },
  {
    id: 'Billing',
    label: 'Digital Bill Generated',
    shortDescription: 'Procurement voucher and calculation slip generated',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Accepted',
  },
  {
    id: 'Payment Processed',
    label: 'Payment Processed',
    shortDescription: 'Direct bank transfer initiated to farmer account',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Billing',
  },
  {
    id: 'Completed',
    label: 'Completed & Archived',
    shortDescription: 'Procurement cycle completed with permanent digital audit trail',
    roleResponsible: 'factory',
    requiredPreviousStage: 'Payment Processed',
    isTerminal: true,
  },
];

export const CROP_WORKFLOWS: Record<CropType, CropWorkflowConfig> = {
  Sugarcane: {
    cropType: 'Sugarcane',
    industry: 'Sugar Industry',
    industryIcon: 'Sprout',
    defaultUnit: 'Metric Tonnes',
    ratePerUnitMsp: 3400, // ₹3,400 per Tonne FRP
    harvestDurationMonths: 12,
    allowedVarieties: ['Co 0238', 'Co 86032', 'Co 0118', 'CoLk 94184', 'VSI 434'],
    qualityParameters: [
      {
        key: 'brixPercentage',
        label: 'Juice Brix (Sucrose %)',
        unit: '%',
        minValue: 14,
        maxValue: 24,
        idealRange: '18% - 21%',
        description: 'Brix measures soluble sucrose solids. Higher brix yields higher sugar recovery.',
      },
      {
        key: 'moisturePercentage',
        label: 'Trash & Binder Binding',
        unit: '%',
        minValue: 0,
        maxValue: 8,
        idealRange: '< 3.0%',
        description: 'Extraneous leaves and tops deducted from gross mill intake.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Cotton: {
    cropType: 'Cotton',
    industry: 'Textile Industry',
    industryIcon: 'Shirt',
    defaultUnit: 'Quintals',
    ratePerUnitMsp: 7120, // ₹7,120 per Quintal
    harvestDurationMonths: 6,
    allowedVarieties: ['Bt Cotton RCH-2', 'Bollgard II', 'MCU-5', 'Suraj', 'DCH-32'],
    qualityParameters: [
      {
        key: 'stapleLengthMm',
        label: 'Fiber Staple Length',
        unit: 'mm',
        minValue: 24,
        maxValue: 36,
        idealRange: '29mm - 32mm',
        description: 'Staple length determines yarn count and spinning strength.',
      },
      {
        key: 'moisturePercentage',
        label: 'Lint Moisture',
        unit: '%',
        minValue: 5,
        maxValue: 14,
        idealRange: '7.5% - 8.5%',
        description: 'Excess moisture leads to fiber discoloration and mold.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Mustard: {
    cropType: 'Mustard',
    industry: 'Oilseed Industry',
    industryIcon: 'Droplet',
    defaultUnit: 'Quintals',
    ratePerUnitMsp: 5650,
    harvestDurationMonths: 4,
    allowedVarieties: ['Pusa Bold', 'RH-30', 'Varuna', 'NRCHB-101', 'Giriraj'],
    qualityParameters: [
      {
        key: 'oilContentPercentage',
        label: 'Oil Content',
        unit: '%',
        minValue: 32,
        maxValue: 46,
        idealRange: '38% - 42%',
        description: 'Crude vegetable oil yield per quintal of mustard seed.',
      },
      {
        key: 'moisturePercentage',
        label: 'Seed Moisture',
        unit: '%',
        minValue: 4,
        maxValue: 12,
        idealRange: '< 8.0%',
        description: 'Safe storage moisture threshold for crushing silos.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Soybean: {
    cropType: 'Soybean',
    industry: 'Oilseed Industry',
    industryIcon: 'Package',
    defaultUnit: 'Quintals',
    ratePerUnitMsp: 4600,
    harvestDurationMonths: 4,
    allowedVarieties: ['JS 335', 'JS 95-60', 'NRC 37', 'MACS 1407', 'RVS 2001-4'],
    qualityParameters: [
      {
        key: 'oilContentPercentage',
        label: 'Oil Content',
        unit: '%',
        minValue: 15,
        maxValue: 23,
        idealRange: '18% - 20%',
        description: 'Solvent extraction edible oil yield.',
      },
      {
        key: 'moisturePercentage',
        label: 'Bean Moisture',
        unit: '%',
        minValue: 6,
        maxValue: 14,
        idealRange: '< 10.0%',
        description: 'Moisture content for soy meal processing.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Sunflower: {
    cropType: 'Sunflower',
    industry: 'Oilseed Industry',
    industryIcon: 'Sun',
    defaultUnit: 'Quintals',
    ratePerUnitMsp: 6760,
    harvestDurationMonths: 3.5,
    allowedVarieties: ['KBSH-1', 'DRSH-1', 'PAC-36', 'MSFH-17', 'Sunbred-275'],
    qualityParameters: [
      {
        key: 'oilContentPercentage',
        label: 'Oil Percentage',
        unit: '%',
        minValue: 30,
        maxValue: 44,
        idealRange: '36% - 40%',
        description: 'Refined sunflower oil recovery potential.',
      },
      {
        key: 'moisturePercentage',
        label: 'Seed Moisture',
        unit: '%',
        minValue: 5,
        maxValue: 12,
        idealRange: '< 9.0%',
        description: 'Moisture for mechanical expeller.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Groundnut: {
    cropType: 'Groundnut',
    industry: 'Oilseed Industry',
    industryIcon: 'Nut',
    defaultUnit: 'Quintals',
    ratePerUnitMsp: 6375,
    harvestDurationMonths: 4,
    allowedVarieties: ['TAG 24', 'JL 24 (Phule Pragati)', 'Kadiri 6', 'TG 37A', 'GG 20'],
    qualityParameters: [
      {
        key: 'oilContentPercentage',
        label: 'Pod Oil Content',
        unit: '%',
        minValue: 38,
        maxValue: 52,
        idealRange: '45% - 49%',
        description: 'Kernel oil fraction.',
      },
      {
        key: 'moisturePercentage',
        label: 'Pod Moisture',
        unit: '%',
        minValue: 5,
        maxValue: 12,
        idealRange: '< 8.0%',
        description: 'Ensures no aflatoxin spore growth during transport.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Tea: {
    cropType: 'Tea',
    industry: 'Tea & Coffee Industry',
    industryIcon: 'Coffee',
    defaultUnit: 'Kilograms',
    ratePerUnitMsp: 28.50,
    harvestDurationMonths: 9,
    allowedVarieties: ['TV 1', 'TV 9', 'UPASI 9', 'AV 2', 'B/5/63'],
    qualityParameters: [
      {
        key: 'moisturePercentage',
        label: 'Fine Leaf Count (Two Leaves & a Bud)',
        unit: '%',
        minValue: 40,
        maxValue: 95,
        idealRange: '> 65%',
        description: 'Ratio of tender tender shoots determining tea liquoring quality.',
      },
    ],
    stages: STANDARD_STAGES,
  },
  Coffee: {
    cropType: 'Coffee',
    industry: 'Tea & Coffee Industry',
    industryIcon: 'Coffee',
    defaultUnit: 'Kilograms',
    ratePerUnitMsp: 85.00,
    harvestDurationMonths: 9,
    allowedVarieties: ['Selection 795', 'Chandragiri', 'Sln 9', 'Robusta CxR', 'Cauvery'],
    qualityParameters: [
      {
        key: 'cuppingScore',
        label: 'Cherry Cupping / Density Score',
        unit: 'pts',
        minValue: 60,
        maxValue: 95,
        idealRange: '80 - 88 pts',
        description: 'Specialty coffee cup profile and ripe cherry uniformity.',
      },
      {
        key: 'moisturePercentage',
        label: 'Parchment Moisture',
        unit: '%',
        minValue: 8,
        maxValue: 16,
        idealRange: '10.5% - 11.5%',
        description: 'Target drying moisture for hulling and export grading.',
      },
    ],
    stages: STANDARD_STAGES,
  },
};
