import React from 'react';
import { BillRecord, ProcurementRecord } from '../../types';
import { Modal } from '../common/Modal';
import { StatusBadge } from '../common/StatusBadge';
import { Printer, CheckCircle, Receipt, Building2, User, Scale } from 'lucide-react';

interface BillReceiptModalProps {
  isOpen: boolean;
  onClose: () => void;
  procurement: ProcurementRecord;
}

export const BillReceiptModal: React.FC<BillReceiptModalProps> = ({
  isOpen,
  onClose,
  procurement,
}) => {
  const bill = procurement.bill;
  if (!bill) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Electronic Procurement Bill & Payment Voucher"
      subtitle={`Generated by ${procurement.factoryName}`}
      maxWidth="lg"
    >
      <div className="space-y-6">
        {/* Invoice Header */}
        <div className="bg-[#F3EFE4] p-4.5 rounded-2xl border border-[#DFD7C4] flex flex-wrap items-center justify-between gap-3">
          <div>
            <span className="text-[10px] uppercase font-bold text-[#777268] tracking-wider">Invoice Number</span>
            <p className="font-mono text-base font-bold text-[#173522]">{bill.billNumber}</p>
            <p className="text-xs text-[#777268] font-sans mt-0.5">Dated: {bill.date}</p>
          </div>
          <div className="text-right">
            <span className="text-[10px] uppercase font-bold text-[#777268] block mb-1 tracking-wider">
              Payment Status
            </span>
            <StatusBadge status={bill.paymentStatus} />
          </div>
        </div>

        {/* Stakeholder Details */}
        <div className="grid grid-cols-2 gap-4 text-xs font-sans">
          <div className="p-3.5 rounded-2xl border border-[#DFD7C4] bg-[#F3EFE4]/40">
            <div className="flex items-center gap-1.5 font-bold text-[#173522] mb-1">
              <User className="w-3.5 h-3.5 text-[#D97824]" />
              <span>Beneficiary Farmer</span>
            </div>
            <p className="font-semibold text-[#171713]">{procurement.farmerName}</p>
            <p className="text-[#777268]">{procurement.farmerPhone}</p>
            <p className="text-[#777268] font-mono text-[11px]">Crop ID: {procurement.cropRegistrationId}</p>
          </div>

          <div className="p-3.5 rounded-2xl border border-[#DFD7C4] bg-[#F3EFE4]/40">
            <div className="flex items-center gap-1.5 font-bold text-[#173522] mb-1">
              <Building2 className="w-3.5 h-3.5 text-[#173522]" />
              <span>Procuring Factory</span>
            </div>
            <p className="font-semibold text-[#171713]">{procurement.factoryName}</p>
            <p className="text-[#777268] font-mono text-[11px]">Batch Ref: {procurement.batchNumber || 'N/A'}</p>
            <p className="text-[#777268]">Crop: {procurement.cropType} ({procurement.variety})</p>
          </div>
        </div>

        {/* Line Item Computation Table */}
        <div className="border border-[#DFD7C4] rounded-2xl overflow-hidden font-sans">
          <table className="w-full text-xs text-left">
            <thead className="bg-[#F3EFE4] text-[#173522] font-semibold border-b border-[#DFD7C4]">
              <tr>
                <th className="p-3">Description</th>
                <th className="p-3 text-right">Net Certified Weight</th>
                <th className="p-3 text-right">Agreed Rate</th>
                <th className="p-3 text-right">Total Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#DFD7C4]/60">
              <tr>
                <td className="p-3">
                  <p className="font-semibold text-[#173522]">
                    {procurement.cropType} ({procurement.variety})
                  </p>
                  <p className="text-[11px] text-[#777268]">
                    Quality Grade: {procurement.quality?.grade || 'Standard'}
                  </p>
                </td>
                <td className="p-3 text-right font-mono font-medium text-[#171713]">
                  {bill.quantityKg.toLocaleString('en-IN')} kg
                  <span className="block text-[10px] text-[#777268]">
                    ({(bill.quantityKg / 1000).toFixed(2)} MT)
                  </span>
                </td>
                <td className="p-3 text-right font-mono font-medium text-[#171713]">
                  ₹{bill.ratePerKg.toFixed(2)} / kg
                </td>
                <td className="p-3 text-right font-mono font-bold text-[#173522] text-sm">
                  ₹{bill.totalAmount.toLocaleString('en-IN')}
                </td>
              </tr>
            </tbody>
            <tfoot className="bg-[#F3EFE4] border-t border-[#DFD7C4] font-bold">
              <tr>
                <td colSpan={3} className="p-3.5 text-right text-[#173522] text-sm">
                  Net Payable Amount:
                </td>
                <td className="p-3.5 text-right font-mono text-[#173522] text-lg font-black">
                  ₹{bill.totalAmount.toLocaleString('en-IN')}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>

        {/* Bank & UTR Reference */}
        {bill.paymentStatus === 'Paid' && bill.transactionRef && (
          <div className="p-4 rounded-2xl bg-[#F3EFE4] border border-[#DFD7C4] flex items-start gap-3">
            <CheckCircle className="w-5 h-5 text-[#173522] shrink-0 mt-0.5" />
            <div className="text-xs text-[#171713] font-sans">
              <p className="font-bold text-[#173522]">Direct Bank Transfer Confirmed</p>
              <p className="mt-0.5 text-[#777268]">
                Funds credited directly to registered farmer bank account via electronic clearing.
              </p>
              <p className="mt-1 font-mono font-semibold text-[#173522]">
                Transaction UTR: {bill.transactionRef}
              </p>
            </div>
          </div>
        )}

        {/* Action Controls */}
        <div className="flex items-center justify-between pt-3 border-t border-[#DFD7C4] font-sans">
          <button
            onClick={handlePrint}
            className="px-4 py-2.5 bg-[#F3EFE4] hover:bg-[#EBE5D6] text-[#173522] border border-[#DFD7C4] rounded-xl text-xs font-semibold flex items-center gap-2 transition cursor-pointer"
          >
            <Printer className="w-4 h-4 text-[#D97824]" />
            <span>Print Voucher</span>
          </button>

          <button
            onClick={onClose}
            className="px-5 py-2.5 bg-[#173522] hover:bg-[#244532] text-[#F3EFE4] rounded-xl text-xs font-semibold transition cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </Modal>
  );
};
